---
- block:
  - name: Install apt-transport-https
    apt:
      name: apt-transport-https
      state: latest
      update_cache: yes

  - name: Run apt update
    apt:
      update_cache: yes
      cache_valid_time: 3600
    register: apt_result
    until: apt_result is success
    retries: 3
    delay: 1
    ignore_errors: yes
    changed_when: no

  - name: Retry if needed using command apt-get update
    command: apt-get update
    when: apt_result is failed
  when: ansible_os_family == "Debian"
