---
- name: Check teleport version
  command: "{{ teleport_bin_path }}/teleport version"
  args:
    chdir: "{{ teleport_bin_path }}"
  register: teleport_check
  ignore_errors: yes
  changed_when: yes

- name: Set teleport_package for Alpine
  set_fact:
    teleport_package: "{{ teleport_alpine_package }}"
    teleport_url: "{{ teleport_alpine_url }}"
  when: (ansible_os_family == "Alpine") and (ansible_architecture == "x86_64")

- name: Set teleport_package for RedHat/Debian
  set_fact:
    teleport_package: "{{ teleport_linux_package }}"
    teleport_url: "{{ teleport_linux_url }}"
  when: (ansible_os_family == "RedHat" or ansible_os_family == "Debian") and (ansible_architecture == "x86_64")

- name: Set teleport_package for ARM architecture
  set_fact:
    teleport_package: "{{ teleport_linux_arm_package }}"
    teleport_url: "{{ teleport_linux_arm_url }}"
  when: (ansible_os_family == "Debian") and (ansible_architecture == "armv7l")

- name: Download teleport package
  get_url:
    url: "{{ teleport_url }}"
    dest: "{{ teleport_releases_path }}"
    validate_certs: "{{ teleport_verify_ssl }}"
  when: (teleport_check is failed or ( teleport_version not in teleport_check.stderr ) or teleport_force_deploy)

- name: Unarchive teleport package
  unarchive:
    copy: no
    src: "{{ teleport_releases_path }}/{{ teleport_package }}"
    dest: /tmp
  when: (teleport_check is failed or ( teleport_version not in teleport_check.stderr ) or teleport_force_deploy)

- name: Copy teleport binary
  copy:
    src: "/tmp/teleport/{{ item }}"
    dest: "{{ teleport_bin_path }}/{{ item }}"
    owner: "{{ teleport_user }}"
    group: "{{ teleport_group }}"
    remote_src: yes
    mode: 0755
  loop:
    - tctl
    - teleport
    - tsh
  notify: restart teleport
  when: is_teleport and (teleport_check is failed or ( teleport_version not in teleport_check.stderr ) or teleport_force_deploy)

- name: Link teleport binary
  file:
    src: "{{ teleport_bin_path }}/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
  loop:
    - tctl
    - teleport
    - tsh
  when: is_teleport
