---
- name: Set roles
  set_fact:
    is_teleport: "{{ inventory_hostname in groups['teleport'] }}"
    is_teleport_auth: "{{ inventory_hostname in groups['teleport-auth'] }}"
    is_teleport_proxy: "{{ inventory_hostname in groups['teleport-proxy'] }}"

- name: Setup prereqs
  include_tasks: prereqs.yml

- name: Install apps
  include_tasks: install.yml

- name: Setup configs
  include_tasks: config.yml

- name: Setup services
  include_tasks: service.yml
